actioncable:
  - changed-files: "actioncable/**/*"
actionmailbox:
  - changed-files: "actionmailbox/**/*"
actionmailer:
  - changed-files: "actionmailer/**/*"
actionpack:
  - changed-files: "actionpack/**/*"
actiontext:
  - changed-files: "actiontext/**/*"
actionview:
  - changed-files: "actionview/**/*"
activejob:
  - changed-files: "activejob/**/*"
activemodel:
  - changed-files: "activemodel/**/*"
activerecord:
  - changed-files: "activerecord/**/*"
activestorage:
  - changed-files: "activestorage/**/*"
activesupport:
  - changed-files: "activesupport/**/*"
rails-ujs:
  - changed-files: "actionview/app/assets/javascripts/rails-ujs/**/*"
railties:
  - changed-files: "railties/**/*"
docs:
  - changed-files: "guides/**/*"
