name: "rails-bot: Label PRs"
on:
  pull_request_target:
  pull_request:
    types: [opened, synchronize]

jobs:
  labeler:
    if: github.repository_owner == 'zzak'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/autolabeler.yml

