name: "rails-bot: Label PRs"
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  labeller:
    if: github.repository_owner == 'zzak'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/autolabeler.yml

