name: "rails-bot: Unstale Issues"

on:
  issues:
    types: [edited, commented]
  issue_comment:
    types: [created]

jobs:
  unstale:
    runs-on: ubuntu-latest
    steps:
    - name: Skip updates from bot
      if: github.actor == 'github-actions'
      run: echo "Comment from bot, skipping job." && exit 0

    - name: Check for stale label
      id: check_stale_label
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const labels = context.payload.issue.labels;
          const hasStaleLabel = labels.some(label => label.name === 'stale');
          return hasStaleLabel;


    - name: Remove stale label if present
      if: steps.check_stale_label.outputs.hasStaleLabel == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.payload.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          await github.issues.removeLabel({
            owner: owner,
            repo: repo,
            issue_number: issueNumber,
            name: 'stale'
          });
